config/routes.rb
Rails.application.routes.draw do
  
  root 'new_home#index'
  get 'index/:boom',to: 'new_home#index',as:"new_home_nav"
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,path: "",path_names:{:sign_in=>"login",sign_out:"logout",sign_up:"register"}


  resources :portfolios ,except: [:show] do
    put :sort , on: :collection
  end

  get 'portfolio/:id', to:"portfolios#show", as: "show_portfolio"

  #root 'pages#home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/tweets'

  #get 'toggle/:id', to:'blogs#bazzinga', as:'toggle'

  resources :blogs do
  	member do
  		post :toggle_status

  	end
  end
  mount ActionCable.server => "/cable"

  delete "bazzinga/:id",to:"comments#destroy",as:"comment"
  #resources :comments
  
  get "topic/:topic_id",to:"blogs#index",as:"blog_topic"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :topic
	enum status:{  draft:0,	published:1	}
	extend FriendlyId
	friendly_id :title, use: :slugged
	validates_presence_of :title,:body,:topic_id
	has_many :comments,dependent: :destroy
	
	def self.recent
		order("created_at DESC")
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_topic_with_blogs, only: [:show,:index]
  before_action :set_topic , except:[:show,:index]
  access all: [:show, :index], user: {except: [:destroy,:new,:create,:update,:edit,:toggle_status]}, site_admin: :all
  layout "blog"
  # GET /blogs
  # GET /blogs.json
  def index
    conditions={}
    if params[:topic_id]
      conditions.merge! topic_id:params[:topic_id]
    end
    if !logged_in?(:site_admin)
      conditions.merge! status:"1"
    end
      @blogs = Blog.recent.page(params[:page]).per(4).where(conditions)
  end
  
  def toggle_status
    #byebug
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    redirect_to blogs_path,notice: "Blog #{@blog.status} "
  end
  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])

      @comment=Comment.new
    else
      redirect_to blogs_path,notice: "You are unauthorized to view this page"
    end

  end

  # GET /blogs/new
  def new
    @blog = Blog.new(topic_id:1)
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    def set_topic_with_blogs
      @topics=Topic.topic_with_blogs
    end
    def set_topic
      @topics=Topic.all
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body,:topic_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper

	def gravatar_helper user
	 image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}",width:60,class:"image-comment"	
	end

	def blog_status_color(blog)
		if blog.draft?
			"color:red;"
		else
			"color:green"
		end
	end

end

app/views/blogs/_admin_toggles.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">          
    <%= link_to fa_icon("pencil"), edit_blog_path(blog),class:"breadcrumb-item"%>
    <%= link_to fa_icon("trash"), blog, method: :delete, data: { confirm: 'Are you sure?' },class:"breadcrumb-item" %>
    <%= link_to fa_icon("file"),toggle_status_blog_path(blog),method: :post,class:"breadcrumb-item",style:blog_status_color(blog)%>
  </ol>
</nav>

app/views/blogs/_blog.html.erb
<div class="col-md-12">
  <div class="card flex-md-row mb-4 box-shadow ">
    
    <div class="card-body d-flex flex-column align-items-start">
      <strong class="d-inline-block mb-2 text-primary"><%= link_to blog.topic.title,blog_topic_path(blog.topic.id) %></strong>
     
      <h3 class="mb-0">
      	<%= link_to blog.title, blog, class:"text-dark" %>
        <!-- <a class="text-dark" href="#"><%= blog.title %></a> -->
      </h3>
      <div class="mb-1 text-muted"><%= time_ago_in_words(blog.created_at)+" ago"%></div>
      <%if logged_in?(:site_admin)%>
        
      <%else%>
        <p class="card-text mb-auto"><%= raw blog.body%></p>
      <%end%>
      <%if logged_in?(:site_admin)%>
        <%=render "blogs/admin_toggles",blog:blog%>
        <%end%>
    </div>
      <%if blog.status=="draft"%>
        <%button="btn btn-danger"%>
      <%else%>
        <%button="btn btn-success"%>
      <%end%>
    	
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error|%>
        <%= alerts(error.to_s)%>
    <%end%>
    
  <% end %>


<div class="card">
  <div class="card-header">
    <div class="form-group">
      <%= form.text_field :title, id: :blog_title,class:"form-control",placeholder: :title %>
    </div>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= form.label :body %></h5>
     <div class="form-group">
      
      <%= form.cktext_area :body, id: :blog_body,class:"form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :topic_id %>
      <%= form.collection_select(:topic_id, @topics,:id,:title,{
        include_blank:false,
      },class:"form-control") %>
    </div>
    <div class="form-group">
      <%= form.submit class:"btn btn-success" %>
    </div>
  </div>

</div>
  
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin)%>
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark covered">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">A thing of Beauty, joy forever.</h1>
          <p class="lead my-3">&nbsp;</p><br><br>
          <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">&nbsp;</a></p>
        </div>
</div>
<%= paginate @blogs%>

<div class="row">

	<div class="col-md-8">
		<div class="row mb-2">
		
		<%= render @blogs%> 
		<%= paginate @blogs%>
	</div>
	</div>
    	<%= render "shared/blog_sidebar"%>
</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        <%=@blog.topic.title%>
      </h3>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <%=link_to "Home",root_path,class:"breadcrumb-item"%>
          <%=link_to "Blogs",blogs_path,class:"breadcrumb-item"%>
          <%= link_to @blog.topic.title,blog_topic_path(@blog.topic.id),class:"breadcrumb-item" %>
          <%=link_to @blog.title,"#",class:"breadcrumb-item active"%>
          
        </ol>
          <span class="pull-right">
            <%=link_to fa_icon("trash"),@blog,method: :delete,data:{confirm:"Are You Sure?"} if logged_in?(:site_admin) %>
          </span>
      </nav>
      <div class="blog-post">
        <h2 class="blog-post-title"><%= @blog.title %></h2>
        <p class="blog-post-meta"><%= time_ago_in_words @blog.created_at %> ago</p>
        <%= @blog.body.html_safe %>
        
      </div><!-- /.blog-post -->

      <nav class="blog-pagination">
        <%= link_to 'Back', blogs_path,class:"btn btn-outline-primary" %>
        <%= link_to 'Edit', edit_blog_path(@blog),class:"btn btn-outline-secondary" if logged_in?(:site_admin) %>
      </nav>
      <%=render 'comments/comment_form',comment:@comment%>

      <div id="comments" data-blog-id="<%= @blog.id %>">
        <%=render @blog.comments%>
      </div>
      <!-- End of comments -->
    </div><!-- /.blog-main -->

    <%= render "shared/blog_sidebar"%>
  </div><!-- /.row -->

</main>