config/routes.rb
Rails.application.routes.draw do
  
  root 'new_home#index'
  get 'index/:boom',to: 'new_home#index',as:"new_home_nav"
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,path: "",path_names:{:sign_in=>"login",sign_out:"logout",sign_up:"register"}


  resources :portfolios ,except: [:show] do
    put :sort , on: :collection
  end

  get 'portfolio/:id', to:"portfolios#show", as: "show_portfolio"

  #root 'pages#home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/tweets'

  #get 'toggle/:id', to:'blogs#bazzinga', as:'toggle'

  resources :blogs do
  	member do
  		post :toggle_status

  	end
  end
  mount ActionCable.server => "/cable"

  delete "bazzinga/:id",to:"comments#destroy",as:"comment"
  #resources :comments
  
  get "topic/:topic_id",to:"blogs#index",as:"blog_topic"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies,dependent: :destroy
	accepts_nested_attributes_for 	:technologies,
									allow_destroy:true,
									reject_if: lambda {|attrs| attrs["name"].blank?}
	validates_presence_of :title,:body

	mount_uploader :thumb_image, PortfolioUploader
	mount_uploader :main_image, PortfolioUploader

	
	def self.angular
		where(subtitle:"Angular")
	end

	scope :ruby_on_rails, -> {where(subtitle:"Ruby on Rails")}

	

	def self.save_sexy(blog)
		
		attribs2=[]
		@blog_technologies=blog.technologies.first.name.split(',')
		@blog_technologies.each do |b|

			attribs2<<{name:b}
		end
		@blog2=Portfolio.new
		@blog2.title=blog.title
		@blog2.body=blog.body
		@blog2.subtitle=blog.subtitle
		#byebug
		@blog2.technologies_attributes=attribs2
		blog.destroy
		return @blog2.save
	end
	def self.by_position
		order("position ASC")
	end
	
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	access all: [:show, :index], user: {except: [:destroy,:new,:create,:update,:edit,:sort]}, site_admin: :all
	layout "portfolio"

	def index
		@portfolio_items=Portfolio.by_position
	end

	def sort
		params[:order].each do |key,value|
			Portfolio.find(value[:id]).update(position: value[:position])
		end
		render body: nil
	end

	def edit
		@portfolio=Portfolio.find(params[:id])
	end

	def new
		@portfolio=Portfolio.new
	end
	
	def show
		@portfolio=Portfolio.find(params[:id])
	end

	def destroy
    	@portfolio=Portfolio.find(params[:id])
    	@portfolio.destroy
    	redirect_to portfolios_path
    end

	def create
	    @blog = Portfolio.new(portfolio_params)
	    #byebug

	    respond_to do |format|
	      #if Portfolio::save_sexy(@blog)
	      if @blog.save
	        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
	        format.json { render :show, status: :created, location: @blog }
	      else
	        format.html { render :new }
	        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
	      end
	    end  
    end
  
    def update
    	@portfolio=Portfolio.find(params[:id])
    	respond_to do |format|
	      if @portfolio.update(portfolio_params)
	        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
	        format.json { render :show, status: :ok, location: @blog }
	      else
	        format.html { render :edit }
	        format.json { render json: @blog.errors, status: :unprocessable_entity }
	      end
    	end
    end

    private 
    
    def portfolio_params
    	params.require(:portfolio).permit(:title, :body,:thumb_image,:main_image,:subtitle,
	    	technologies_attributes:[:id,:name,:_destroy])
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper


def image_generator(height,width)
	"http://via.placeholder.com/#{height}x#{width}"
end

def portfolio_img img,style
	
	if img.model.main_image? || img.model.thumb_image?
		img
	elsif style=="thumb"
		image_generator(350,200)
	elsif style=="main"
		image_generator(600,400)		
	end
end

end

app/views/portfolios/_form.html.erb
<div class="container portfolio-container">
  
  <%= form_with(model: data, local: true) do |form|%>
    <% if data.errors.any? %>
      <% data.errors.full_messages.each do |error|%>
          <%= alerts(error) %>
      <%end%>
  <% end %>

    <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, id: :blog_title,class:"form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :subtitle %>
            <%= form.text_field :subtitle, id: :blog_title,class:"form-control" %>
          </div>
          <div>
            <label class="btn btn-success">
              Upload Main Image<%= form.file_field :main_image,style:"display: none;"%>
            </label>
            
          </div>
          <div>
            <label class="btn btn-success">
              Upload Thumb Image<%= form.file_field :thumb_image,style:"display: none;"%>
            </label>
            
          </div>
        </div>
        
        <div class="col-md-6">
          <%=form.fields_for :technologies do|tech|%>
            <%= render 'technology_fields', f: tech%>
          <%end%>
        <div>
          <%=link_to_add_association 'Add Technology',form,:technologies%>
        </div>
        </div>

        

        <div class="col-md-12">
          <div class="form-group">
            <%= form.label :body %>
            <%= form.cktext_area :body, id: :blog_body %>
          </div>
          <div class="form-group">
            <%= form.submit class:"btn btn-primary btn-block" %>
          </div>
        </div>   
    </div>    
  <% end %>
</div>

app/views/portfolios/_portfolio.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow" data-id="<%=portfolio.id%>">
    <%=image_tag portfolio_img(portfolio.thumb_image,"thumb"),class:"card-img-top",width:"100%"%>
    <div class="card-body">
      <p class="card-title"><%=link_to portfolio.title,show_portfolio_path(portfolio.id)%></p>
      <p class="card-text"><%=portfolio.subtitle%></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
    	     <%= button_to "Edit",edit_portfolio_path(portfolio),method:"get",class:"btn btn-sm btn-outline-secondary" if logged_in?(:site_admin)%>
           <%= button_to "Delete",portfolio_path(portfolio),method:"delete",data:{confirm:"Are you Sure?"},class:"btn btn-sm btn-outline-secondary" if logged_in?(:site_admin)%>
        </div>
        <small class="text-muted"><%=time_ago_in_words(portfolio.created_at)%></small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
	<%=f.label :name%>
	<%=f.text_field :name,class:"form-control"%>
	<%=link_to_remove_association '&#8634;'.html_safe,f%>
</div>

app/views/portfolios/edit.html.erb
<%=render 'form',data:@portfolio%>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
	<p><%=button_to "New",new_portfolio_path,method:"get",class:"btn btn-success btn-block" if logged_in?(:site_admin)%></p>
	<div class="container">
	  <div class="row <%='sortable' if logged_in?(:site_admin)%>">

			<%= render partial:"portfolio",collection: @portfolio_items%>

	  </div>
	</div>
</div>

app/views/portfolios/new.html.erb
<%=render 'form',data:@portfolio%>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
	<div class="row">
		<div class="col-md-7">
			<%=image_tag portfolio_img(@portfolio.main_image,"main"),width:"100%"%>
		</div>
		<div class="col-md-5">
				<h1><%=@portfolio.title%></h1>
				<h3><%=@portfolio.subtitle%></h3>

				<p><%=raw @portfolio.body%></p>
				<h3>Technologies Used:</h3>
				<%@portfolio.technologies.each do |f|%>
				<p><%=f.name%></p>
				<%end%>
				<%if logged_in?(:site_admin)%>
					<div>
						<%= link_to "Edit",edit_portfolio_path(@portfolio),class:"btn btn-warning"%>
					</div>
				<%end%>
		</div>
		
	</div>
</div>