config/routes.rb
Rails.application.routes.draw do
  
  root 'new_home#index'
  get 'index/:boom',to: 'new_home#index',as:"new_home_nav"
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,path: "",path_names:{:sign_in=>"login",sign_out:"logout",sign_up:"register"}


  resources :portfolios ,except: [:show] do
    put :sort , on: :collection
  end

  get 'portfolio/:id', to:"portfolios#show", as: "show_portfolio"

  #root 'pages#home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/tweets'

  #get 'toggle/:id', to:'blogs#bazzinga', as:'toggle'

  resources :blogs do
  	member do
  		post :toggle_status

  	end
  end
  mount ActionCable.server => "/cable"

  delete "bazzinga/:id",to:"comments#destroy",as:"comment"
  #resources :comments
  
  get "topic/:topic_id",to:"blogs#index",as:"blog_topic"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_about.html.erb
I began my Journey as an average student, living the average life, being the average person.
But I always had in intention of having, from being a class flunker to a topper, from being a waterboy to a state level goalie, from being a computer hater to a computer lover, I have always achieved what I wanted.

app/views/shared/_alerts.html.erb
<%= alerts %>

app/views/shared/_blog_sidebar.html.erb
<aside class="blog-sidebar col-md-4">
          <div class="p-3 mb-3 bg-light rounded">
            <h4 class="font-italic">About</h4>
            <p class="mb-0"><%=render "shared/about"%></p>
          </div>
          <%=session_module("alert alert-success")%>
          <!-- Make a topic panel for topics that have blogs -->
          <%if @topics%>
            <div class="p-3">
              <h4 class="font-italic">Topics</h4>
              <ol class="list-unstyled mb-0">
                <%@topics.each do |topic|%>
                  <li><%= link_to topic.title,blog_topic_path(topic.id)%></li>
                <%end%>
              </ol>
            </div>
          <%end%>

          <div class="p-3">
            <h4 class="font-italic">Elsewhere</h4>
            <div class="social-links">
              <a href="https://github.com/stingrayzboy/" target="_blank"><%=fa_icon "github"%></a>&nbsp;&nbsp;
              <a href="https://twitter.com/FarazNoor7" target="_blank"><%=fa_icon "twitter"%></a>&nbsp;&nbsp;
              <a href="https://www.facebook.com/StingrayzF" target="_blank"><%=fa_icon "facebook"%></a>&nbsp;&nbsp;
              <a href="https://www.linkedin.com/in/go-get-faraz/" target="_blank"><%=fa_icon "linkedin"%></a>&nbsp;&nbsp;
              <a href="mailto:faraznoor75@gmail.com?subject=DevCamp" target="_blank"><%=fa_icon "at"%></a>&nbsp;&nbsp;
            </div>
          </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_footer.html.erb
<footer class="mastfoot mt-auto">
      <div class="inner">
        <p class="football">
        <%=set_copyright%></p>
      </div>
</footer>

app/views/shared/_nav_bar.html.erb
<header class="masthead mb-auto">
	<div class="inner">
		<h3 class="masthead-brand">Faraz Noor</h3>
		<nav class="nav nav-masthead app-nav">
        	<%= nav_helper 'nav-link', '','' %>
            <%=logged_in "nav-link"%>
        </nav>
    </div>
</header>

app/views/shared/_nav_bar_blog.html.erb
<header class="blog-header py-3">
	<div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            
          </div>
		<div class="col-4 text-center">
            <%=link_to "Faraz Noor",root_path,class:"blog-header-logo text-dark"%>
            
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%=logged_in "btn btn-sm btn-outline-secondary"%>
        </div>
		
    </div>
</header>

<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        <%= nav_helper 'p-2 text-muted', '','' %>
        
    </nav>
</div>

app/views/shared/_nav_bar_portfolio.html.erb
<div class="col-sm-4 offset-md-1 py-4">
      <h4 class="text-white">Contact</h4>
      <ul class="list-unstyled">
        <%= nav_helper 'text-white', '<li>','</li>' %>
        <li><%=logged_in "text-white"%></li>
      </ul>
</div>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">My Portfolios</h1>
      <p class="lead text-muted">A list of projects I have worked upon</p>
      <p>
      	<%=link_to "Portfolios",portfolios_path,class:"btn btn-primary my-2"%>
      	<%=link_to "My Blogs",blogs_path,class:"btn btn-secondary my-2"%>
        
      </p>
    </div>
</section>