config/routes.rb
Rails.application.routes.draw do
  
  root 'new_home#index'
  get 'index/:boom',to: 'new_home#index',as:"new_home_nav"
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,path: "",path_names:{:sign_in=>"login",sign_out:"logout",sign_up:"register"}


  resources :portfolios ,except: [:show] do
    put :sort , on: :collection
  end

  get 'portfolio/:id', to:"portfolios#show", as: "show_portfolio"

  #root 'pages#home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/tweets'

  #get 'toggle/:id', to:'blogs#bazzinga', as:'toggle'

  resources :blogs do
  	member do
  		post :toggle_status

  	end
  end
  mount ActionCable.server => "/cable"

  delete "bazzinga/:id",to:"comments#destroy",as:"comment"
  #resources :comments
  
  get "topic/:topic_id",to:"blogs#index",as:"blog_topic"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<main role="main" class="inner cover">
	<div class="app-about-container">    
	    <div class="card">
		    <div class="row">  
		    	<h1 class="cover-heading">“I don’t have dreams, I have goals.”</h1>  
			    <div class="col-md-6">
			    	
			    	<div class="covered">&nbsp;</div>
			    	<div class="collapse" id="skill_history">
			    		<%@skills.each do |skill|%>
			    			<h4><%=skill.title%></h4>
				    		<div class="card-block">
				    			<div class="progress">
				    				<div 
				    					class="progress-bar progress-bar-striped bg-warning"
				    					role="progressbar"
				    					aria-valuenow="<%=skill.percent_utilized%>"
				    					aria-valuemax="100"
				    					style="width: <%=skill.percent_utilized%>%"
				    				></div>
				    			</div>
				    		</div>
			    		<%end%>
			    	</div>
			    </div>
			    <div class="col-md-6">   
			        
			        <p class="lead">
			        	<%=render "shared/about"%>
			        </p>
			        <p>
			        	<button
			        		class="btn btn-primary"
			        		type="button"
			        		data-toggle="collapse"
			        		data-target="#job_history"
			        		aria-expanded="false"
			        		aria-controler="job_history"
			        	>Jobs</button>
			        	<button
			        		class="btn btn-warning"
			        		type="button"
			        		data-toggle="collapse"
			        		data-target="#school_history"
			        		aria-expanded="false"
			        		aria-controler="school_history"
			        	>Education</button>
			        	<button
			        		class="btn btn-danger"
			        		type="button"
			        		data-toggle="collapse"
			        		data-target="#skill_history"
			        		aria-expanded="false"
			        		aria-controler="skill_history"
			        	>Skills</button>
			        </p>
			       
				    <div class="collapse" id="job_history">
				    	<div class="card card-block">Tata Consultancy Services</div>
				    </div>
				    <div class="collapse" id="school_history">
				    	<div class="card card-block">University of Mumbai</div>
				    </div>
			    </div> 
			</div>
		</div>
	</div>
    	
</main>

app/views/pages/contact.html.erb
<main role="main" class="inner cover">
    <div class="app-about-container">    
        <div class="card">    
            <h1 class="cover-heading">Would you like to work together?</h1>
            <div class="row">
            	<div class="col-md-6">
            		
            		<div>
                        <h4>Email</h4>
                        <a href="mailto:faraznoor75@gmail.com?subject=PortfolioContact" target="_blank">faraznoor75@gmail.com</a>
                    </div>
            		
            	</div>
            	<div class="col-md-6">
            		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3559.7128779198483!2d80.94990776489661!3d26.849083133155013!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399bfd0f9731bfa7%3A0xf1b7ad1911833d44!2sGanga+sagar+Complex+(Ramtirth+Marg)%2C+Ramtirth+Marg%2C+Narhi%2C+Hazratganj%2C+Lucknow%2C+Uttar+Pradesh+226001!5e0!3m2!1sen!2sin!4v1521235944070" width="300" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            	</div>
            </div>
              <%link_to "My Blogs",blogs_path,class:"btn btn-lg btn-secondary" %>
            </p>
        </div>
    </div>
</main>

app/views/pages/home.html.erb
	<main role="main" class="inner cover">
        <h1 class="cover-heading">Welcome</h1>
        <p class="lead">
        	Software development is like an art,anybody can do it with the basic knowledge,but you need to love what you do inorder to achieve a masterpiece.<br>

        </p>
        <p class="lead">
          <%=link_to "About Me",pages_about_path,class:"btn btn-lg btn-secondary"%>
        </p>
    </main>

app/views/pages/tweets.html.erb
<h2 class="container">Live Tweets about Ruby on Rails</h2>
<div class="row">
  <%@tweets.each do |tweet|%>
  <div class="card col-md-4">
      <div class="twitter">
        <div class="card-title"><%=tweet.split(":").first%></div>
        <%tweet.slice!(tweet.split(":").first+":")%>
        <%=twitter_parser tweet%>
      </div>
  </div>
  <%end%>
</div>